name: rencode
description: "Obscure encoding standard used in the Deluge torrent client and its RPC APIs."

version: 0.0.5
homepage: https://github.com/teal77/dart-rencode

environment:
  sdk: '>=2.12.1 <3.0.0'

dev_dependencies:
  test: "^1.16.8"
  pedantic: "^1.11.0"